services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    network_mode: "host"
    restart: unless-stopped
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    env_file:
      - ./client/.env